# Application settings
# log_level             -> Log verbosity level
[app]
log_level = "debug"


# Host settings
# port                  -> Port to run the server on
# domain                -> Domain used to host the server on
# cors                  -> Allowed cors origins
[host]
port = 8080
domain = "localhost"
cors = ["http://localhost:5173"]


# SSL settings
# enabled               -> Toggles secure connections (https)
# certificate_path      -> Path to your SSL certificate
# certificate_key_path  -> Path to your SSL certificate key
[host.ssl]
enabled = false
certificate_path = ""
certificate_key_path = ""


# FFmpeg settings
# path                  -> Path to your ffmpeg install (not needed if in $PATH)
# hwaccel_flags         -> Hardware acceleration flags (disabled if not set)
# max_jobs              -> Max amount of jobs that cna be in the queue
# workers               -> Max amount of concurrent jobs to run
[ffmpeg]
path = ""
hwaccel_flags = ""
max_jobs = 20
workers = 4

# JWT settings
# secret                -> Secret string used for token encoding/validation
[jwt]
secret = ""


# Storage settings
# type                  -> Type of storage to use (e.g., "local", "s3")
# max_usage             -> Maximum usage in bytes allowed for storage
[storage]
type = "s3"
max_usage = 10_000_000_000


# Upload settings
# max_size              -> Maximum file size for uploads
# allowed_types         -> List of allowed file types for uploading.
# NOTE: File types other than the ones provided by default aren't supported yet.
[upload]
max_size = 2_000_000_000
allowed_types = ["video/mp4"]


# AWS settings
# access_key            -> AWS S3 access key ID
# secret_access_key     -> AWS S3 secret access key
# bucket                -> S3 bucket to store data in
[aws]
access_key = ""
secret_access_key = ""
region = ""
bucket = ""


# Turnstile settings
# enabled               -> Toggles turnstile
# secret_token          -> Used to validate challenge results to avoid bots
[cloudflare.turnstile]
enabled = false
secret_token = ""